global using System.IO;
global using Application = System.Windows.Application;
global using MessageBox = Wpf.Ui.Violeta.Controls.MessageBox;
global using ContentDialog = Wpf.Ui.Violeta.Controls.ContentDialog;
global using Control = System.Windows.Controls.Control;
global using ContentDialogButton = Wpf.Ui.Violeta.Controls.ContentDialogButton;
global using ContentDialogResult = Wpf.Ui.Violeta.Controls.ContentDialogResult;
global using Color = System.Windows.Media.Color;
global using static TiktokLiveRec.LocaleExtension;
global using Toast = TiktokLiveRec.Toast;
